# Stage 1: Build
FROM golang:1.24.2-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o node ./cmd/node

# Stage 2: Run
FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/node .

CMD ["./node","get","storage/warp/ngo.pdf.json"]