# Stage 1: Build
FROM golang:1.24.2-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o tracker ./cmd/tracker

# Stage 2: Run
FROM alpine:latest

RUN apk add --no-cache redis

WORKDIR /root/

COPY --from=builder /app/tracker .

COPY start-tracker.sh .
RUN chmod +x ./start-tracker.sh

CMD ["./start-tracker.sh"]