// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: proto/tracker/tracker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetResourceHoldersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileHash      string                 `protobuf:"bytes,1,opt,name=FileHash,proto3" json:"FileHash,omitempty"`
	Status        []bool                 `protobuf:"varint,2,rep,packed,name=Status,proto3" json:"Status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceHoldersRequest) Reset() {
	*x = GetResourceHoldersRequest{}
	mi := &file_proto_tracker_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceHoldersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceHoldersRequest) ProtoMessage() {}

func (x *GetResourceHoldersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceHoldersRequest.ProtoReflect.Descriptor instead.
func (*GetResourceHoldersRequest) Descriptor() ([]byte, []int) {
	return file_proto_tracker_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *GetResourceHoldersRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *GetResourceHoldersRequest) GetStatus() []bool {
	if x != nil {
		return x.Status
	}
	return nil
}

type RegisterResourceHolderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileHash      string                 `protobuf:"bytes,1,opt,name=FileHash,proto3" json:"FileHash,omitempty"`
	Status        []bool                 `protobuf:"varint,2,rep,packed,name=Status,proto3" json:"Status,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResourceHolderRequest) Reset() {
	*x = RegisterResourceHolderRequest{}
	mi := &file_proto_tracker_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResourceHolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResourceHolderRequest) ProtoMessage() {}

func (x *RegisterResourceHolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResourceHolderRequest.ProtoReflect.Descriptor instead.
func (*RegisterResourceHolderRequest) Descriptor() ([]byte, []int) {
	return file_proto_tracker_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResourceHolderRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *RegisterResourceHolderRequest) GetStatus() []bool {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RegisterResourceHolderRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetResourceHoldersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Holder        map[int64]*HolderRow   `protobuf:"bytes,1,rep,name=Holder,proto3" json:"Holder,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceHoldersResponse) Reset() {
	*x = GetResourceHoldersResponse{}
	mi := &file_proto_tracker_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceHoldersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceHoldersResponse) ProtoMessage() {}

func (x *GetResourceHoldersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceHoldersResponse.ProtoReflect.Descriptor instead.
func (*GetResourceHoldersResponse) Descriptor() ([]byte, []int) {
	return file_proto_tracker_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *GetResourceHoldersResponse) GetHolder() map[int64]*HolderRow {
	if x != nil {
		return x.Holder
	}
	return nil
}

type HolderRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []string               `protobuf:"bytes,1,rep,name=Ips,proto3" json:"Ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolderRow) Reset() {
	*x = HolderRow{}
	mi := &file_proto_tracker_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderRow) ProtoMessage() {}

func (x *HolderRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderRow.ProtoReflect.Descriptor instead.
func (*HolderRow) Descriptor() ([]byte, []int) {
	return file_proto_tracker_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *HolderRow) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_tracker_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tracker_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_tracker_tracker_proto_rawDescGZIP(), []int{4}
}

var File_proto_tracker_tracker_proto protoreflect.FileDescriptor

var file_proto_tracker_tracker_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74,
	0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x4f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x08, 0x52,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x6d, 0x0a, 0x1d, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x08, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xb4, 0x01, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x48, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x1a, 0x4d,
	0x0a, 0x0b, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52,
	0x6f, 0x77, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x1d, 0x0a,
	0x09, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x52, 0x6f, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x49, 0x70, 0x73, 0x22, 0x07, 0x0a, 0x05,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xc1, 0x01, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x12, 0x22,
	0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x12, 0x26, 0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_tracker_tracker_proto_rawDescOnce sync.Once
	file_proto_tracker_tracker_proto_rawDescData []byte
)

func file_proto_tracker_tracker_proto_rawDescGZIP() []byte {
	file_proto_tracker_tracker_proto_rawDescOnce.Do(func() {
		file_proto_tracker_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tracker_tracker_proto_rawDesc), len(file_proto_tracker_tracker_proto_rawDesc)))
	})
	return file_proto_tracker_tracker_proto_rawDescData
}

var file_proto_tracker_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_tracker_tracker_proto_goTypes = []any{
	(*GetResourceHoldersRequest)(nil),     // 0: tracker.GetResourceHoldersRequest
	(*RegisterResourceHolderRequest)(nil), // 1: tracker.RegisterResourceHolderRequest
	(*GetResourceHoldersResponse)(nil),    // 2: tracker.GetResourceHoldersResponse
	(*HolderRow)(nil),                     // 3: tracker.HolderRow
	(*Empty)(nil),                         // 4: tracker.Empty
	nil,                                   // 5: tracker.GetResourceHoldersResponse.HolderEntry
}
var file_proto_tracker_tracker_proto_depIdxs = []int32{
	5, // 0: tracker.GetResourceHoldersResponse.Holder:type_name -> tracker.GetResourceHoldersResponse.HolderEntry
	3, // 1: tracker.GetResourceHoldersResponse.HolderEntry.value:type_name -> tracker.HolderRow
	0, // 2: tracker.TrackerService.GetResourceHolders:input_type -> tracker.GetResourceHoldersRequest
	1, // 3: tracker.TrackerService.RegisterResourceHolder:input_type -> tracker.RegisterResourceHolderRequest
	2, // 4: tracker.TrackerService.GetResourceHolders:output_type -> tracker.GetResourceHoldersResponse
	4, // 5: tracker.TrackerService.RegisterResourceHolder:output_type -> tracker.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tracker_tracker_proto_init() }
func file_proto_tracker_tracker_proto_init() {
	if File_proto_tracker_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tracker_tracker_proto_rawDesc), len(file_proto_tracker_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tracker_tracker_proto_goTypes,
		DependencyIndexes: file_proto_tracker_tracker_proto_depIdxs,
		MessageInfos:      file_proto_tracker_tracker_proto_msgTypes,
	}.Build()
	File_proto_tracker_tracker_proto = out.File
	file_proto_tracker_tracker_proto_goTypes = nil
	file_proto_tracker_tracker_proto_depIdxs = nil
}
